### ISSUE TITLE
使用私钥连接报错

### ISSUE THREAD

**Issue by Yurunsoft** [beckzhu/SimpleRemote#11]
RT：
![image](https://user-images.githubusercontent.com/20104656/57749543-03002000-7711-11e9-8a15-49289d88917f.png)

**Comment by Yurunsoft** [comment]
应该是这个问题导致了，我重新保存成.ppk就可以，还是希望能够支持一下旧的格式
Unable to use key file "C:\Users\Yurun\AppData\Local\Temp\5cdb9d585551ba37c4046bde" (OpenSSH SSH-2 private key (old PEM format))

**Comment by beckzhu** [comment]
抱歉   短时间内不会支持旧的格式，由于putty不支持，要改这些东西就比较费劲，先会考虑解决其他问题,后续会慢慢完善这些细节的问题  谢谢支持
