### ISSUE TITLE
RDP 连接错误 错误代码-4

### ISSUE THREAD

**Issue by zhangyongbo** [beckzhu/SimpleRemote#13]
RDP服务器开启多用户登录，且目前没有用户连接的情况下，使用软件会报错误。如果使用windows远程桌面连接进行连接后，本软件就可以进入。2个连接进入的是不同的会话

**Comment by beckzhu** [comment]
暂时还测试过多个用户登入的问题  后续我会测试下，谢谢支持

**Comment by beckzhu** [comment]
[SimpleRemote.zip](https://github.com/beckzhu/SimpleRemote/files/3512088/SimpleRemote.zip)
麻烦试试新版本  谢谢支持
