### ISSUE TITLE
远程连接信息保存问题

### ISSUE THREAD

**Issue by GeekCatPYG** [beckzhu/SimpleRemote#14]
请问远程连接信息在什么位置，能不能把这些信息保存在软件当前目录或其它地方，一是如果这些信息是放在C盘，在重做系统时会不事先复制出来就会丢，二是更换电脑或把软件复制到其它电脑上使用时之前保存的信息带不过去。

**Comment by beckzhu** [comment]
C:\ProgramData\SimpleRemote   后续会支持多种设置   谢谢支持

**Comment by beckzhu** [comment]
新版本已经支持
