### ISSUE TITLE
连接信息复制粘贴需求

### ISSUE THREAD

**Issue by GeekCatPYG** [beckzhu/SimpleRemote#15]
需求：要建立了多个连接时，当我们建好1个连接后再建第2个连接时。
第2连接信息跟前一个或之前的建好的连接只有很少一部分信息不同，如果可以直接复制之前建立好的连接再粘贴出一个新连接再修改部分信息就变成一个新连接了。
这样可以大节约时间。

**Comment by beckzhu** [comment]
后续会考虑 加入复制的功能  谢谢支持

**Comment by beckzhu** [comment]
1.2已支持复制粘贴
