### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by vampniklaus** [beckzhu/SimpleRemote#18]
![批注 2019-06-08 162856](https://user-images.githubusercontent.com/24869042/59144461-eeaafc80-8a0a-11e9-918a-81e2e002fbda.jpg)

**Comment by beckzhu** [comment]
已修复http://www.91fk.net可下载。   谢谢支持

**Comment by vampniklaus** [comment]
![am8_20190616132302704](https://user-images.githubusercontent.com/24869042/59559436-e457b680-9039-11e9-8ea8-d6aeeb67d85a.jpg)
RDP连接报错，错误代码2055

**Comment by beckzhu** [comment]
[SimpleRemote.zip](https://github.com/beckzhu/SimpleRemote/files/3512088/SimpleRemote.zip)
麻烦试试新版本  谢谢支持
