### ISSUE TITLE
新建RDP连接,直接命名回车后异常退出

### ISSUE THREAD

**Issue by mestars** [beckzhu/SimpleRemote#19]
新建RDP连接,直接命名回车后异常退出。直接在目录树上修改名称回车也是异常退出。 注意：我加了分组。

**Comment by beckzhu** [comment]
[SimpleRemote.zip](https://github.com/beckzhu/SimpleRemote/files/3512088/SimpleRemote.zip)
麻烦试试新版本  谢谢支持
