### ISSUE TITLE
软件卡顿问题

### ISSUE THREAD

**Issue by ttbug** [beckzhu/SimpleRemote#6]
软件很清爽，但是使用的时候标签会经常无响应，而且点击最大化窗口直接就全屏了，系统是win10

**Comment by beckzhu** [comment]
最大化窗口直接全屏  是软件本身的设置，标签会经常无响应是不是用ssh跟Telnet的时候会这样？

**Comment by ttbug** [comment]
对的，使用ssh的时候，标签会经常无响应

**Comment by beckzhu** [comment]
麻烦帮忙试试新版是否有问题

下载地址：http://ucloud.91fk.net/SimpleRemote(5.12).zip

**Comment by ttbug** [comment]
> 麻烦帮忙试试新版是否有问题
> 
> 下载地址：http://ucloud.91fk.net/SimpleRemote(5.12).zip

不卡顿了，还有一个问题哈，就是一个ssh连接只能打开一个标签吗，我如果想打开多个标签好像不行，还有就是已经连接了一个ssh以后，再右键打开(后台)或者打开（外部），之前的连接都会变成正在连接，请稍后。

**Comment by ttbug** [comment]
> 是的 哪种场景下需要打开两个 ssh?

我觉得这个场景应该比较常见的哈，比如我同时开两个窗口，一个用来实时观察日志输出，另外一个用来修改代码或者调试程序这种，感觉还是挺常见的

**Comment by beckzhu** [comment]
新版本已支持多个ssh连接
