### ISSUE TITLE
自定义端口

### ISSUE THREAD

**Issue by lasypig** [beckzhu/SimpleRemote#7]
能否添加自定义端口设置，一些ssh和telnet不是用的默认端口。

**Comment by beckzhu** [comment]
可以的  使用: 号  如  192.168.1.1:300

**Comment by lasypig** [comment]
冒号+端口号，一直显示：正在连接，请稍候。。。

**Comment by beckzhu** [comment]
麻烦告知下操作系统版本




------------------ 原始邮件 ------------------
发件人: "lasypig"<notifications@github.com>; 
发送时间: 2019年5月10日(星期五) 上午9:40
收件人: "beckzhu/SimpleRemote"<SimpleRemote@noreply.github.com>; 
抄送: "Beck"<1010795186@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [beckzhu/SimpleRemote] 自定义端口 (#7)




冒号+端口号，一直显示：正在连接，请稍候。。。

**Comment by lasypig** [comment]
win10

**Comment by beckzhu** [comment]
我这边测试的时候是正常的。  您那边能否用putty  试下连接

**Comment by lasypig** [comment]
我在服务器上抓包看了下，telnet服务器发过来提示登录的字符串（XXX login:）之后，Simpleemote没有往服务器发送用户名，直到服务器判断登录超时。是不是一些时候调用putty时得到的用户名密码为空阿。

**Comment by beckzhu** [comment]
是这样的，本工具是基于putty的    你可以试试putty能不能连




------------------ 原始邮件 ------------------
发件人: "lasypig"<notifications@github.com>; 
发送时间: 2019年5月12日(星期天) 上午10:09
收件人: "beckzhu/SimpleRemote"<SimpleRemote@noreply.github.com>; 
抄送: "Beck"<1010795186@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [beckzhu/SimpleRemote] 自定义端口 (#7)




我在服务器上抓包看了下，telnet服务器发过来提示登录的字符串（XXX login:）之后，Simpleemote没有往服务器发送用户名，直到服务器判断登录超时。是不是一些时候调用putty时得到的用户名密码为空阿。

**Comment by lasypig** [comment]
![TIM图片20190512140706](https://user-images.githubusercontent.com/1818233/57578449-6f83e080-74bf-11e9-8fe1-d70e92b22fd2.png)
可以的

**Comment by beckzhu** [comment]
@我在服务器上抓包看了下，telnet服务器发过来提示登录的字符串（XXX login:）之后，Simpleemote没有往服务器发送用户名，直到服务器判断登录超时。是不是一些时候调用putty时得到的用户名密码为空阿。
你指的是   当用户名密码为空的时候， telnet就不能连接吗？   不为空的时候就可以 ？

**Comment by beckzhu** [comment]
![Snipaste_2019-05-12_21-07-28](https://user-images.githubusercontent.com/32129001/57582684-5b110980-74fa-11e9-8126-edc59a18338f.png)
![Snipaste_2019-05-12_21-07-49](https://user-images.githubusercontent.com/32129001/57582685-5b110980-74fa-11e9-84ad-679caafeddf3.png)
如果是这样的话，请将putty连接练的日志发下给我，我确认是是否忽略了哪个事件。

**Comment by lasypig** [comment]
2019-05-13 09:14:45	Connecting to 192.168.157.53 port 3123
2019-05-13 09:14:45	client:	WILL NAWS
2019-05-13 09:14:45	client:	WILL TSPEED
2019-05-13 09:14:45	client:	WILL TTYPE
2019-05-13 09:14:45	client:	WILL NEW_ENVIRON
2019-05-13 09:14:45	client:	DO ECHO
2019-05-13 09:14:45	client:	WILL SGA
2019-05-13 09:14:45	client:	DO SGA
2019-05-13 09:14:45	server:	DO ECHO
2019-05-13 09:14:45	client:	WONT ECHO
2019-05-13 09:14:45	server:	DO NAWS
2019-05-13 09:14:45	client:	SB NAWS 80,24
2019-05-13 09:14:45	server:	WILL ECHO
2019-05-13 09:14:45	server:	WILL SGA

**Comment by beckzhu** [comment]
麻烦帮忙试试新版是否有问题
[SimpleRemote(5.13).zip](https://github.com/beckzhu/SimpleRemote/files/3173127/SimpleRemote.5.13.zip)

**Comment by lasypig** [comment]
不会卡在“正在连接”了，该输入用户名的地方输入的是密码，然后提示输入密码。

**Comment by beckzhu** [comment]
能否发下图

**Comment by lasypig** [comment]
![TIM截图20190515102007](https://user-images.githubusercontent.com/1818233/57744272-1f915d80-76fb-11e9-87d4-634ee35cfcd3.png)

**Comment by beckzhu** [comment]
[SimpleRemote.zip](https://github.com/beckzhu/SimpleRemote/files/3182993/SimpleRemote.zip)
试试这个

**Comment by lasypig** [comment]
![TIM截图20190516215240](https://user-images.githubusercontent.com/1818233/57859187-08e72580-7825-11e9-8688-d961770f7d77.png)

**Comment by beckzhu** [comment]
[Uploading SimpleRemote.zip…]()
试试这个看看会弹出啥提示

**Comment by beckzhu** [comment]
[SimpleRemote.zip](https://github.com/beckzhu/SimpleRemote/files/3187504/SimpleRemote.zip)
试试这个看看会弹出啥提示

**Comment by lasypig** [comment]
![TIM图片20190517091806](https://user-images.githubusercontent.com/1818233/57896741-c6553580-7884-11e9-9f09-cb72e49eebea.png)
用户名密码填的都有

**Comment by lasypig** [comment]
...
