### ISSUE TITLE
RDP全屏时，有时候工具栏出不来

### ISSUE THREAD

**Issue by aushy** [beckzhu/SimpleRemote#8]
RDP全屏时，有时候工具栏出不来，就没法关掉了。
win7 x64

**Comment by AlphaJP** [comment]
我也遇到了这样的问题
win10 x64

**Comment by beckzhu** [comment]
麻烦帮忙试试新版是否有问题

下载地址：http://ucloud.91fk.net/SimpleRemote(5.12).zip

**Comment by GeekCatPYG** [comment]
我也遇到了这样的问题
win7 x64
软件版本：1.1.0.0(2019.05.14)
可以在"远程桌面设置"的组合键设置为“在这台计算上”，这时可以切出来，但这时的组合键不能在远程的电脑使用，如果在组合键处不这样设置就切不出来全屏。

**Comment by beckzhu** [comment]
远程桌面上方没有工具栏出来吗？




------------------ 原始邮件 ------------------
发件人: "GeekCatPYG"<notifications@github.com>; 
发送时间: 2019年5月15日(星期三) 晚上8:35
收件人: "beckzhu/SimpleRemote"<SimpleRemote@noreply.github.com>; 
抄送: "Beck"<1010795186@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [beckzhu/SimpleRemote] RDP全屏时，有时候工具栏出不来 (#8)




我也遇到了这样的问题
 win7 x64 
 软件版本：1.1.0.0(2019.05.14) 
 可以在"远程桌面设置"的组合键设置为“在这台计算上”，这时可以切出来，但这时的组合键不能在远程的电脑使用，如果在组合键处不这样设置就切不出来全屏。

**Comment by beckzhu** [comment]
远程桌面上方没有工具栏出来吗？，如果是这样的话，这种情况是偶然，还是必然？




------------------ 原始邮件------------------
发件人: "GeekCatPYG"<notifications@github.com>;
发送时间: 2019年5月15日(星期三)晚上8:35
收件人: "beckzhu/SimpleRemote"<SimpleRemote@noreply.github.com>;
抄送: "Beck"<1010795186@qq.com>; "Comment"<comment@noreply.github.com>;
主题: Re: [beckzhu/SimpleRemote] RDP全屏时，有时候工具栏出不来(#8)




我也遇到了这样的问题
 win7 x64 
 软件版本：1.1.0.0(2019.05.14) 
 可以在"远程桌面设置"的组合键设置为“在这台计算上”，这时可以切出来，但这时的组合键不能在远程的电脑使用，如果在组合键处不这样设置就切不出来全屏。

**Comment by GeekCatPYG** [comment]
> 远程桌面上方没有工具栏出来吗？，如果是这样的话，这种情况是偶然，还是必然？
> […](#)
> ------------------ 原始邮件------------------ 发件人: "GeekCatPYG"<notifications@github.com>; 发送时间: 2019年5月15日(星期三)晚上8:35 收件人: "beckzhu/SimpleRemote"<SimpleRemote@noreply.github.com>; 抄送: "Beck"<1010795186@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [beckzhu/SimpleRemote] RDP全屏时，有时候工具栏出不来(#8) 我也遇到了这样的问题 win7 x64 软件版本：1.1.0.0(2019.05.14) 可以在"远程桌面设置"的组合键设置为“在这台计算上”，这时可以切出来，但这时的组合键不能在远程的电脑使用，如果在组合键处不这样设置就切不出来全屏。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or mute the thread .

远程桌面上方工具栏会在远程连接成功后会出现几秒钟随后就消失
我跟我同事都试了，都遇到同样的问题
我同事的系统是win10 X64

**Comment by beckzhu** [comment]
能否  抽空我远程看下，这个问题在我这边没有遇到过

**Comment by AlphaJP** [comment]
最新版本（5.12）也是这个问题，目前就@GeekCatPYG 说的方法可行，“Alt + Tab”切换回自己的电脑

**Comment by GeekCatPYG** [comment]
> 能否 抽空我远程看下，这个问题在我这边没有遇到过

远程不了，我这边的服务器都在内网，而且是内外网是两套布线物理分离的，我有时间我录一段视频发你邮箱。

**Comment by beckzhu** [comment]
好的  谢谢

**Comment by beckzhu** [comment]
不需要录制下来了  我这边也触发了这个bug  已经有了新的解决方案

**Comment by beckzhu** [comment]
新版本已解决
